"""remove token, add last access

Revision ID: b6a3bfcc703f
Revises: fd81122f2c77
Create Date: 2019-04-16 13:04:16.744174

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b6a3bfcc703f'
down_revision = 'fd81122f2c77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_access', sa.DateTime(), nullable=True))
    op.drop_index('ix_user_token', table_name='user')
    op.drop_column('user', 'token')
    op.drop_column('user', 'token_expiration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token_expiration', mysql.DATETIME(), nullable=True))
    op.add_column('user', sa.Column('token', mysql.VARCHAR(length=32), nullable=True))
    op.create_index('ix_user_token', 'user', ['token'], unique=True)
    op.drop_column('user', 'last_access')
    # ### end Alembic commands ###
