"""add html_format and md_format

Revision ID: caf1e21e3a79
Revises: d80884c44835
Create Date: 2019-04-21 10:10:03.454510

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'caf1e21e3a79'
down_revision = 'd80884c44835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('html_format', sa.Text(), nullable=True))
    op.add_column('post', sa.Column('md_format', sa.Text(), nullable=True))
    op.drop_column('post', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body', mysql.TEXT(), nullable=True))
    op.drop_column('post', 'md_format')
    op.drop_column('post', 'html_format')
    # ### end Alembic commands ###
